export enum ConfigurationName {
	DAILY_AVERAGE_KM = 'DAILY_AVERAGE_KM',
	FUEL_PRICE = 'FUEL_PRICE',
	ELECTRICITY_PRICE_HOME_SOLAR = 'ELECTRICITY_PRICE_HOME_SOLAR',
	ELECTRICITY_PRICE_HOME_NOSOLAR = 'ELECTRICITY_PRICE_HOME_NOSOLAR',
	ELECTRICITY_PRICE_PUBLIC_SLOW = 'ELECTRICITY_PRICE_PUBLIC_SLOW',
	ELECTRICITY_PRICE_PUBLIC_FAST = 'ELECTRICITY_PRICE_PUBLIC_FAST'
}

export interface IConfigurationValues {
	[ConfigurationName.DAILY_AVERAGE_KM]: number;
	[ConfigurationName.FUEL_PRICE]: number;
	[ConfigurationName.ELECTRICITY_PRICE_HOME_SOLAR]: number;
	[ConfigurationName.ELECTRICITY_PRICE_HOME_NOSOLAR]: number;
	[ConfigurationName.ELECTRICITY_PRICE_PUBLIC_SLOW]: number;
	[ConfigurationName.ELECTRICITY_PRICE_PUBLIC_FAST]: number;
}

